# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pratik/Desktop/runner

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pratik/Desktop/runner

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pratik/Desktop/runner/CMakeFiles /home/pratik/Desktop/runner/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pratik/Desktop/runner/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named runner

# Build rule for target.
runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runner
.PHONY : runner

# fast build rule for target.
runner/fast:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/build
.PHONY : runner/fast

add.o: add.cpp.o

.PHONY : add.o

# target to build an object file
add.cpp.o:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/add.cpp.o
.PHONY : add.cpp.o

add.i: add.cpp.i

.PHONY : add.i

# target to preprocess a source file
add.cpp.i:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/add.cpp.i
.PHONY : add.cpp.i

add.s: add.cpp.s

.PHONY : add.s

# target to generate assembly for a file
add.cpp.s:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/add.cpp.s
.PHONY : add.cpp.s

grab.o: grab.cpp.o

.PHONY : grab.o

# target to build an object file
grab.cpp.o:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/grab.cpp.o
.PHONY : grab.cpp.o

grab.i: grab.cpp.i

.PHONY : grab.i

# target to preprocess a source file
grab.cpp.i:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/grab.cpp.i
.PHONY : grab.cpp.i

grab.s: grab.cpp.s

.PHONY : grab.s

# target to generate assembly for a file
grab.cpp.s:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/grab.cpp.s
.PHONY : grab.cpp.s

ran.o: ran.cpp.o

.PHONY : ran.o

# target to build an object file
ran.cpp.o:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/ran.cpp.o
.PHONY : ran.cpp.o

ran.i: ran.cpp.i

.PHONY : ran.i

# target to preprocess a source file
ran.cpp.i:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/ran.cpp.i
.PHONY : ran.cpp.i

ran.s: ran.cpp.s

.PHONY : ran.s

# target to generate assembly for a file
ran.cpp.s:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/ran.cpp.s
.PHONY : ran.cpp.s

runner.o: runner.cpp.o

.PHONY : runner.o

# target to build an object file
runner.cpp.o:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/runner.cpp.o
.PHONY : runner.cpp.o

runner.i: runner.cpp.i

.PHONY : runner.i

# target to preprocess a source file
runner.cpp.i:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/runner.cpp.i
.PHONY : runner.cpp.i

runner.s: runner.cpp.s

.PHONY : runner.s

# target to generate assembly for a file
runner.cpp.s:
	$(MAKE) -f CMakeFiles/runner.dir/build.make CMakeFiles/runner.dir/runner.cpp.s
.PHONY : runner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... runner"
	@echo "... edit_cache"
	@echo "... add.o"
	@echo "... add.i"
	@echo "... add.s"
	@echo "... grab.o"
	@echo "... grab.i"
	@echo "... grab.s"
	@echo "... ran.o"
	@echo "... ran.i"
	@echo "... ran.s"
	@echo "... runner.o"
	@echo "... runner.i"
	@echo "... runner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

